spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Grupo-16-BDD-OO2-2021
    username: root
    password: 123456789
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false